/**
 * Airport & City Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, in test this API only contains data from the United States, Spain, United Kingdom, Germany and India. 
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Address { 
    /**
     * name of the city of the location; equal to name if the location is a city
     */
    cityName?: string;
    /**
     * IATA code of the city of the location; equal to IATAcode if the location is a city
     */
    cityCode?: string;
    /**
     * name of the country of the location
     */
    countryName?: string;
    /**
     * code of the country of the location in ISO standard
     */
    countryCode?: string;
    /**
     * code of the state of the location if any
     */
    stateCode?: string;
    /**
     * code of the region of the location in ISO standard
     */
    regionCode?: string;
}
