/**
 * Airport & City Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, in test this API only contains data from the United States, Spain, United Kingdom, Germany and India. 
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Links { 
    href: string;
    methods?: Array<Links.MethodsEnum>;
    count?: number;
}
export namespace Links {
    export type MethodsEnum = 'GET' | 'PUT' | 'DELETE' | 'POST' | 'PATCH';
    export const MethodsEnum = {
        GET: 'GET' as MethodsEnum,
        PUT: 'PUT' as MethodsEnum,
        DELETE: 'DELETE' as MethodsEnum,
        POST: 'POST' as MethodsEnum,
        PATCH: 'PATCH' as MethodsEnum
    };
}
