/**
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AdditionalInformation { 
    /**
     * If true, returns the price of the first additional bag when the airline is an \"Amadeus Ancillary Services\" member.
     */
    chargeableCheckedBags?: boolean;
    /**
     * If true, returns the fare family name for each flight-offer which supports fare family
     */
    brandedFares?: boolean;
}
