/**
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * Restriction towards carriers.
 */
export interface CarrierRestrictions { 
    /**
     * This flag enable/disable filtering of blacklisted airline by EU. The list of the banned airlines is published in the Official Journal of the European Union, where they are included as annexes A and B to the Commission Regulation. The blacklist of an airline can concern all its flights or some specific aircraft types pertaining to the airline
     */
    blacklistedInEUAllowed?: boolean;
    /**
     * This option ensures that the system will only consider these airlines.
     */
    excludedCarrierCodes?: Array<string>;
    /**
     * This option ensures that the system will only consider these airlines.
     */
    includedCarrierCodes?: Array<string>;
}
