/**
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * part of the trip covered by the travel class restriction (ALL_SEGMENTS if ommited)
 */
export type Coverage = 'MOST_SEGMENTS' | 'AT_LEAST_ONE_SEGMENT' | 'ALL_SEGMENTS';

export const Coverage = {
    MOSTSEGMENTS: 'MOST_SEGMENTS' as Coverage,
    ATLEASTONESEGMENT: 'AT_LEAST_ONE_SEGMENT' as Coverage,
    ALLSEGMENTS: 'ALL_SEGMENTS' as Coverage
};
