/**
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdditionalServicesRequest } from './additionalServicesRequest';
import { AllotmentDetails } from './allotmentDetails';
import { BaggageAllowance } from './baggageAllowance';
import { SliceDiceIndicator } from './sliceDiceIndicator';
import { TravelClass } from './travelClass';


/**
 * Fare details of the segment
 */
export interface FareDetailsBySegment { 
    /**
     * Id of the segment
     */
    segmentId: string;
    cabin?: TravelClass;
    /**
     * Fare basis specifying the rules of a fare. Usually, though not always, is composed of the booking class code followed by a set of letters and digits representing other characteristics of the ticket, such as refundability, minimum stay requirements, discounts or special promotional elements.
     */
    fareBasis?: string;
    /**
     * The name of the Fare Family corresponding to the fares. Only for the GDS provider and if the airline has fare families filled
     */
    brandedFare?: string;
    /**
     * The code of the booking class, a.k.a. class of service or Reservations/Booking Designator (RBD)
     */
    _class?: string;
    /**
     * True if the corresponding booking class is in an allotment
     */
    isAllotment?: boolean;
    allotmentDetails?: AllotmentDetails;
    sliceDiceIndicator?: SliceDiceIndicator;
    /**
     * Details of the included checked bags
     */
    includedCheckedBags?: BaggageAllowance;
    additionalServices?: AdditionalServicesRequest;
}
