/**
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AircraftEquipment } from './aircraftEquipment';
import { FlightEndPoint } from './flightEndPoint';
import { FlightStop } from './flightStop';
import { OperatingFlight } from './operatingFlight';


/**
 * defining a flight segment; including both operating and marketing details when applicable
 */
export interface FlightSegment { 
    departure?: FlightEndPoint;
    arrival?: FlightEndPoint;
    /**
     * providing the airline / carrier code
     */
    carrierCode?: string;
    /**
     * the flight number as assigned by the carrier
     */
    number?: string;
    aircraft?: AircraftEquipment;
    operating?: OperatingFlight;
    /**
     * stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M
     */
    duration?: string;
    /**
     * information regarding the different stops composing the flight segment. E.g. technical stop, change of gauge...
     */
    stops?: Array<FlightStop>;
}
