/**
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ExtendedPrice } from './extendedPrice';
import { FareRules } from './fareRules';
import { FlightOfferSource } from './flightOfferSource';
import { Itineraries } from './itineraries';
import { PricingOptions } from './pricingOptions';
import { TravelerPricing } from './travelerPricing';


export interface FlightOffer { 
    /**
     * the resource name
     */
    type: string;
    /**
     * Id of the flight offer
     */
    id: string;
    source?: FlightOfferSource;
    /**
     * If true, inform that a ticketing will be required at booking step.
     */
    instantTicketingRequired?: boolean;
    /**
     * BOOK step ONLY - If true, allows to book a PNR without pricing. Only for the source \"GDS\"
     */
    disablePricing?: boolean;
    /**
     * If true, upon completion of the booking, this pricing solution is expected to yield multiple records (a record contains booking information confirmed and stored, typically a Passenger Name Record (PNR), in the provider GDS or system)
     */
    nonHomogeneous?: boolean;
    /**
     * If true, the flight offer fulfills only one originDestination and has to be combined with other oneWays to complete the whole journey.
     */
    oneWay?: boolean;
    /**
     * If true, a payment card is mandatory to book this flight offer
     */
    paymentCardRequired?: boolean;
    /**
     * If booked on the same day as the search (with respect to timezone), this flight offer is guaranteed to be thereafter valid for ticketing until this date (included). Unspecified when it does not make sense for this flight offer (e.g. no control over ticketing once booked). YYYY-MM-DD format, e.g. 2019-06-07
     */
    lastTicketingDate?: string;
    /**
     * Number of seats bookable in a single request. Can not be higher than 9.
     */
    numberOfBookableSeats?: number;
    itineraries?: Array<Itineraries>;
    price?: ExtendedPrice;
    pricingOptions?: PricingOptions;
    /**
     * This option ensures that the system will only consider these airlines.
     */
    validatingAirlineCodes?: Array<string>;
    /**
     * Fare information for each traveler/segment
     */
    travelerPricings?: Array<TravelerPricing>;
    /**
     * Fare rules of the flight offer
     */
    fareRules?: FareRules;
}
