/**
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CabinRestriction } from './cabinRestriction';
import { CarrierRestrictions } from './carrierRestrictions';
import { ConnectionRestriction } from './connectionRestriction';


export interface FlightFilters { 
    /**
     * Allows to search a location outside the borders when a radius around a location is specified. Default is false.
     */
    crossBorderAllowed?: boolean;
    /**
     * This flag enables/disables the possibility to have more overnight flights in Low Fare Search
     */
    moreOvernightsAllowed?: boolean;
    /**
     * This option force to retrieve flight-offer with a departure and a return in the same airport
     */
    returnToDepartureAirport?: boolean;
    /**
     * This flag enable/disable filtering of rail segment (TGV AIR, RAIL ...)
     */
    railSegmentAllowed?: boolean;
    /**
     * This flag enable/disable filtering of bus segment
     */
    busSegmentAllowed?: boolean;
    /**
     * This option allows to modify the value for the Elapsed Flying Time (EFT) masterPricer option
     */
    maxFlightTime?: number;
    carrierRestrictions?: CarrierRestrictions;
    /**
     * Restriction towards cabins.
     */
    cabinRestrictions?: Array<CabinRestriction>;
    connectionRestriction?: ConnectionRestriction;
}
