/**
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FlightOfferSource } from './flightOfferSource';
import { OriginDestination } from './originDestination';
import { SearchCriteria } from './searchCriteria';
import { Traveler } from './traveler';


export interface GetFlightOffersQuery { 
    /**
     * The currency code, as defined in [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217), to reflect the currency in which this amount is expressed.
     */
    currencyCode?: string;
    /**
     * Origins and Destinations must be properly ordered in time (chronological order in accordance with the timezone of each location) to describe the journey consistently. Dates and times must not be past nor more than 365 days in the future, according to provider settings.Number of Origins and Destinations must not exceed the limit defined in provider settings.
     */
    originDestinations: Array<OriginDestination>;
    travelers: Array<Traveler>;
    /**
     * Allows enable one or more sources. If present in the list, these sources will be called by the system.
     */
    sources: Array<FlightOfferSource>;
    searchCriteria?: SearchCriteria;
}
