/**
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DateTimeRange } from './dateTimeRange';


export interface OriginDestination { 
    id?: string;
    /**
     * Origin location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported.
     */
    originLocationCode?: string;
    /**
     * Include other possible locations around the point, located less than this distance in kilometers away. Max:300  Can not be combined with \"dateWindow\" or \"timeWindow\". 
     */
    originRadius?: number;
    /**
     * Set of alternative origin location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported.
     */
    alternativeOriginsCodes?: Array<string>;
    /**
     * Destination location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported.
     */
    destinationLocationCode?: string;
    /**
     * Include other possible locations around the point, located less than this distance in kilometers away. Max:300  Can not be combined with \"dateWindow\" or \"timeWindow\". 
     */
    destinationRadius?: number;
    /**
     * Set of alternative destination location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported.
     */
    alternativeDestinationsCodes?: Array<string>;
    /**
     * Approximate date and time of departure, specified as a local date and time range.
     */
    departureDateTimeRange?: DateTimeRange;
    /**
     * Approximate date and time of arrival, specified as a local date and time range.
     */
    arrivalDateTimeRange?: DateTimeRange;
    /**
     * List of included connections points. When an includedViaPoints option is specified, all FlightOffer returned must at least go via this Connecting Point. Currently, only the locations defined in IATA are supported. Used only by the AMADEUS provider
     */
    includedConnectionPoints?: Array<string>;
    /**
     * List of excluded connections points. Any FlightOffer with these connections points will be present in response. Currently, only the locations defined in IATA are supported. Used only by the AMADEUS provider
     */
    excludedConnectionPoints?: Array<string>;
}
