/**
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AdditionalInformation } from './additionalInformation';
import { ExtendedPricingOptions } from './extendedPricingOptions';
import { FlightFilters } from './flightFilters';


export interface SearchCriteria { 
    /**
     * This option allows to exclude the isAllotment flag associated to a booking class in the search response when it exist.
     */
    excludeAllotments?: boolean;
    /**
     * This option allows activate the one-way combinable feature
     */
    addOneWayOffers?: boolean;
    /**
     * Maximum number of flight offers returned (Max 250)
     */
    maxFlightOffers?: number;
    /**
     * maximum price per traveler. By default, no limit is applied. If specified, the value should be a positive number with no decimals
     */
    maxPrice?: number;
    /**
     * This option allows to default to a standard fareOption if no offers are found for the selected fareOption.
     */
    allowAlternativeFareOptions?: boolean;
    /**
     * Requests the system to find at least one flight-offer per day, if possible, when a range of dates is specified. Default is false.
     */
    oneFlightOfferPerDay?: boolean;
    additionalInformation?: AdditionalInformation;
    pricingOptions?: ExtendedPricingOptions;
    flightFilters?: FlightFilters;
}
