/**
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * slice and Dice indicator, such as Local Availability, Sub OnD(Origin and Destination) 1 Availability and Sub OnD 2 Availability
 */
export type SliceDiceIndicator = 'LOCAL_AVAILABILITY' | 'SUB_OD_AVAILABILITY_1' | 'SUB_OD_AVAILABILITY_2';

export const SliceDiceIndicator = {
    LOCALAVAILABILITY: 'LOCAL_AVAILABILITY' as SliceDiceIndicator,
    SUBODAVAILABILITY1: 'SUB_OD_AVAILABILITY_1' as SliceDiceIndicator,
    SUBODAVAILABILITY2: 'SUB_OD_AVAILABILITY_2' as SliceDiceIndicator
};
