/**
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * traveler type age restrictions : CHILD < 12y, HELD_INFANT < 2y, SEATED_INFANT < 2y, SENIOR >=60y 
 */
export type TravelerType = 'ADULT' | 'CHILD' | 'SENIOR' | 'YOUNG' | 'HELD_INFANT' | 'SEATED_INFANT' | 'STUDENT';

export const TravelerType = {
    ADULT: 'ADULT' as TravelerType,
    CHILD: 'CHILD' as TravelerType,
    SENIOR: 'SENIOR' as TravelerType,
    YOUNG: 'YOUNG' as TravelerType,
    HELDINFANT: 'HELD_INFANT' as TravelerType,
    SEATEDINFANT: 'SEATED_INFANT' as TravelerType,
    STUDENT: 'STUDENT' as TravelerType
};
