/**
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TravelerType } from './travelerType';


export interface Traveler { 
    id: string;
    travelerType: TravelerType;
    /**
     * if type=\"HELD_INFANT\", corresponds to the adult travelers's id who will share the seat
     */
    associatedAdultId?: string;
}
