/**
 * Flight Offers Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, if you are not returning any results try with big cities/airports like LON (London) or NYC (New-York).
 *
 * OpenAPI spec version: 2.3.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * option specifying a group of fares, which may be valid under certain conditons Can be used to specify special fare discount for a passenger 
 */
export type TravelerPricingFareOption = 'STANDARD' | 'INCLUSIVE_TOUR' | 'SPANISH_MELILLA_RESIDENT' | 'SPANISH_CEUTA_RESIDENT' | 'SPANISH_CANARY_RESIDENT' | 'SPANISH_BALEARIC_RESIDENT' | 'AIR_FRANCE_METROPOLITAN_DISCOUNT_PASS' | 'AIR_FRANCE_DOM_DISCOUNT_PASS' | 'AIR_FRANCE_COMBINED_DISCOUNT_PASS' | 'AIR_FRANCE_FAMILY' | 'ADULT_WITH_COMPANION' | 'COMPANION';

export const TravelerPricingFareOption = {
    STANDARD: 'STANDARD' as TravelerPricingFareOption,
    INCLUSIVETOUR: 'INCLUSIVE_TOUR' as TravelerPricingFareOption,
    SPANISHMELILLARESIDENT: 'SPANISH_MELILLA_RESIDENT' as TravelerPricingFareOption,
    SPANISHCEUTARESIDENT: 'SPANISH_CEUTA_RESIDENT' as TravelerPricingFareOption,
    SPANISHCANARYRESIDENT: 'SPANISH_CANARY_RESIDENT' as TravelerPricingFareOption,
    SPANISHBALEARICRESIDENT: 'SPANISH_BALEARIC_RESIDENT' as TravelerPricingFareOption,
    AIRFRANCEMETROPOLITANDISCOUNTPASS: 'AIR_FRANCE_METROPOLITAN_DISCOUNT_PASS' as TravelerPricingFareOption,
    AIRFRANCEDOMDISCOUNTPASS: 'AIR_FRANCE_DOM_DISCOUNT_PASS' as TravelerPricingFareOption,
    AIRFRANCECOMBINEDDISCOUNTPASS: 'AIR_FRANCE_COMBINED_DISCOUNT_PASS' as TravelerPricingFareOption,
    AIRFRANCEFAMILY: 'AIR_FRANCE_FAMILY' as TravelerPricingFareOption,
    ADULTWITHCOMPANION: 'ADULT_WITH_COMPANION' as TravelerPricingFareOption,
    COMPANION: 'COMPANION' as TravelerPricingFareOption
};
