/**
 * Airport & City Search
 *  Before using this API, we recommend you read our **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)** for more information on how to generate an access token.   Please also be aware that our test environment is based on a subset of the production, in test this API only contains data from the United States, Spain, United Kingdom, Germany and India. 
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { Error400 } from '../model/error400';
import { Error500 } from '../model/error500';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class LocationsService {

    protected basePath = 'https://test.api.amadeus.com/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Returns a list of airports and cities matching a given keyword.
     * 
     * @param subType sub type of the location (AIRPORT and/or CITY)
     * @param keyword keyword that should represent the start of a word in a city or airport name or code
     * @param countryCode Country code of the location using [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code format (e.g. US).
     * @param pageLimit maximum items in one page
     * @param pageOffset start index of the requested page
     * @param sort defines on which attribute the sorting will be done: * analytics.travelers.score - sort by the number of travelers by airport or city, the airports and cities with the highest traffic are on top of the results 
     * @param view select the level of information of the reply: * LIGHT - Gives only the IATACode, name, detailedName, cityName and countryName * FULL - Adds on top of the LIGHT information the timeZoneOffset, geocode, detailed address and travelers.score default option is FULL 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAirportCitySearch(subType: Array<'AIRPORT' | 'CITY'>, keyword: string, countryCode?: string, pageLimit?: number, pageOffset?: number, sort?: 'analytics.travelers.score', view?: 'LIGHT' | 'FULL', observe?: 'body', reportProgress?: boolean): Observable<any>;
    public getAirportCitySearch(subType: Array<'AIRPORT' | 'CITY'>, keyword: string, countryCode?: string, pageLimit?: number, pageOffset?: number, sort?: 'analytics.travelers.score', view?: 'LIGHT' | 'FULL', observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public getAirportCitySearch(subType: Array<'AIRPORT' | 'CITY'>, keyword: string, countryCode?: string, pageLimit?: number, pageOffset?: number, sort?: 'analytics.travelers.score', view?: 'LIGHT' | 'FULL', observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public getAirportCitySearch(subType: Array<'AIRPORT' | 'CITY'>, keyword: string, countryCode?: string, pageLimit?: number, pageOffset?: number, sort?: 'analytics.travelers.score', view?: 'LIGHT' | 'FULL', observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (subType === null || subType === undefined) {
            throw new Error('Required parameter subType was null or undefined when calling getAirportCitySearch.');
        }

        if (keyword === null || keyword === undefined) {
            throw new Error('Required parameter keyword was null or undefined when calling getAirportCitySearch.');
        }






        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (subType) {
            queryParameters = queryParameters.set('subType', subType.join(COLLECTION_FORMATS['csv']));
        }
        if (keyword !== undefined && keyword !== null) {
            queryParameters = queryParameters.set('keyword', <any>keyword);
        }
        if (countryCode !== undefined && countryCode !== null) {
            queryParameters = queryParameters.set('countryCode', <any>countryCode);
        }
        if (pageLimit !== undefined && pageLimit !== null) {
            queryParameters = queryParameters.set('page[limit]', <any>pageLimit);
        }
        if (pageOffset !== undefined && pageOffset !== null) {
            queryParameters = queryParameters.set('page[offset]', <any>pageOffset);
        }
        if (sort !== undefined && sort !== null) {
            queryParameters = queryParameters.set('sort', <any>sort);
        }
        if (view !== undefined && view !== null) {
            queryParameters = queryParameters.set('view', <any>view);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/vnd.amadeus+json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/vnd.amadeus+json'
        ];

        return this.httpClient.get<any>(`${this.basePath}/reference-data/locations`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
