/**
 * Safe Place and Authorization
 *  This API incorporates Auth flow to obtain access token. For more details visit **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)**.     Please also be aware that our test environment is based on a subset of the production, this API in test only returns a few selected cities. You can find the list in our **[data collection](https://github.com/amadeus4dev/data-collection)**.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Links { 
    href: string;
    methods?: Array<Links.MethodsEnum>;
    count?: number;
}
export namespace Links {
    export type MethodsEnum = 'GET' | 'PUT' | 'DELETE' | 'POST' | 'PATCH';
    export const MethodsEnum = {
        GET: 'GET' as MethodsEnum,
        PUT: 'PUT' as MethodsEnum,
        DELETE: 'DELETE' as MethodsEnum,
        POST: 'POST' as MethodsEnum,
        PATCH: 'PATCH' as MethodsEnum
    };
}
