/**
 * Safe Place and Authorization
 *  This API incorporates Auth flow to obtain access token. For more details visit **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)**.     Please also be aware that our test environment is based on a subset of the production, this API in test only returns a few selected cities. You can find the list in our **[data collection](https://github.com/amadeus4dev/data-collection)**.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SafetyScore { 
    /**
     * Likelihood of inappropriate behavior against females. Score go from 1 (not likely) to 100 (very likely).
     */
    women?: number;
    /**
     * Likelihood of injury due to harmful intent. Score go from 1 (not likely) to 100 (very likely).
     */
    physicalHarm?: number;
    /**
     * Likelihood of theft. Score go from 1 (not likely) to 100 (very likely).
     */
    theft?: number;
    /**
     * Potential for infringement of political rights or political unrest. Score go from 1 (not likely) to 100 (very likely).
     */
    politicalFreedom?: number;
    /**
     * Likelihood of harm or discrimination against LGBTQ persons or groups and level of caution required at location. Score go from 1 (not likely) to 100 (very likely).
     */
    lgbtq?: number;
    /**
     * Likelihood of illness or disease, assessment of water and air quality, and access to reliable medical care. Score go from 1 (not likely) to 100 (very likely).
     */
    medical?: number;
    /**
     * An average of the 6 “sub”-categories. Score go from 1 (very safe) to 100 (very dangerous).
     */
    overall?: number;
}
