/**
 * Safe Place and Authorization
 *  This API incorporates Auth flow to obtain access token. For more details visit **[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization)**.     Please also be aware that our test environment is based on a subset of the production, this API in test only returns a few selected cities. You can find the list in our **[data collection](https://github.com/amadeus4dev/data-collection)**.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GeoCode } from './geoCode';
import { Links } from './links';


/**
 * price information
 */
export interface SafetyRatedLocation { 
    /**
     * id of the ressource
     */
    id?: string;
    self?: Links;
    /**
     * the resource name
     */
    type?: string;
    /**
     * location sub type
     */
    subType?: SafetyRatedLocation.SubTypeEnum;
    /**
     * short name of the location
     */
    name?: string;
    geoCode?: GeoCode;
}
export namespace SafetyRatedLocation {
    export type SubTypeEnum = 'AIRPORT' | 'CITY' | 'POINT_OF_INTEREST' | 'DISTRICT';
    export const SubTypeEnum = {
        AIRPORT: 'AIRPORT' as SubTypeEnum,
        CITY: 'CITY' as SubTypeEnum,
        POINTOFINTEREST: 'POINT_OF_INTEREST' as SubTypeEnum,
        DISTRICT: 'DISTRICT' as SubTypeEnum
    };
}
